### Create user
POST http://localhost:5267/api/users
Content-Type: application/json

{
  "name": "Jon",
  "email": "userA@example.com"
}

### Create user
POST http://localhost:5267/api/users
Content-Type: application/json

{
  "name": "Bob",
  "email": "userB@example.com"
}

### Create user
POST http://localhost:5267/api/users
Content-Type: application/json

{
  "name": "Anna",
  "email": "userC@example.com"
}

### temp data
@user1Id = 1fb23288-ea09-4160-bd1f-57323c7526bc
@user2Id = 879d9069-3e20-4180-aa37-c4ee85cd55c5
@user3Id = 00000000-0000-0000-0000-000000000003
@chatId = 69e9c839-2801-42a9-aa82-fc9a7d280e84

# 🚨 Убедитесь, что порт ChatService соответствует вашему запуску (например, 7011 или 5001)
@chatServiceUrl = http://localhost:5000

### Presonal chat Create
POST {{chatServiceUrl}}/api/chats/personal
Content-Type: application/json

{
  "user1Id": "{{user1Id}}",
  "user2Id": "{{user2Id}}"
}

### Group Chat Create
POST {{chatServiceUrl}}/api/chats/group
Content-Type: application/json

{
  "name": "Group Chat",
  "participantIds": [
    "{{user1Id}}",
    "{{user2Id}}",
    "{{user3Id}}"
  ]
}

### Get Chat by ID
GET {{chatServiceUrl}}/api/chats/{{chatId}}
Accept: application/json

### Get all user chats
GET {{chatServiceUrl}}/api/chats/user/{{user1Id}}
Accept: application/json

### Create chat with non-existent user ( 400 Bad Request)
# Используйте фиктивный ID, чтобы увидеть проверку ChatService
POST {{chatServiceUrl}}/api/chats/personal
Content-Type: application/json

{
  "user1Id": "00000000-0000-0000-0000-000000000001",
  "user2Id": "deadbeef-dead-beef-dead-beefdeadbeef"
}