### Create user
POST http://localhost:5267/api/users
Content-Type: application/json

{
  "name": "Руслан",
  "email": "ruslan@example.com"
}


### Get user by id ID
@userId = 879d9069-3e20-4180-aa37-c4ee85cd55c5

GET http://localhost:5267/api/users/{{userId}}
Accept: application/json


### Invalid reqest (NotFound)
GET http://localhost:5267/api/users/00000000-0000-0000-0000-000000000000
Accept: application/json